Punkt_Serwisowy/Punkt_Serwisowy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),

    path('electronic_service/', include('electronic_service.urls')),
    path('electronic_service/', TemplateView.as_view(template_name='electronic_service/indexcopy.html'), name='home'),
]

Punkt_Serwisowy/accounts/urls.py
from django.urls import path
from . import views

# from .views import SignUpView

app_name = "account"

urlpatterns = [
    path("signup/", views.register_client, name="signup"),
    path("signup/result", views.register_client_result, name="signup_result"),
]

Punkt_Serwisowy/electronic_service/urls.py
from django.urls import path
from . import views

app_name = 'electronic_service'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('profile/delete', views.profile_delete, name='profile_delete'),
    path('profile/delete/result', views.profile_delete_result, name='profile_delete_result'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
    path('profile/edit/result', views.profile_edit_result, name='profile_edit_result'),
    path('request_service/', views.make_request, name='make_request'),
    path('request_service/result', views.make_request_result, name='make_request_result'),
    path('request_service/add_hardware_to_<int:request_id>', views.add_request_hardware, name='add_request_hardware'),

    path('employee/client_list', views.client_list_E_P, name='client_list'),
    path('employee/hardware_list', views.hardware_list_E_P, name='hardware_list'),
    path('employee/hardware_fault_list', views.hardware_fault_list_E_P, name='hardware_fault_list'),
    path('employee/service_request_list', views.request_list_E_P, name='service_request_list'),
    path('employee/spare_parts_list', views.spare_parts_list_E_P, name='spare_parts_list'),
    path('employee/profile', views.profile_E_P, name='employee_profile'),
    path('employee/profile/edit', views.profile_edit_E_P, name='employee_profile_edit'),
    path('employee/profile/edit/result', views.profile_edit_result_E_P, name='employee_profile_edit_result'),

]

Punkt_Serwisowy/electronic_service/models.py
import datetime

from django.urls import reverse
from django.db import models
from django.utils import timezone


class employee(models.Model):
    name = models.CharField(max_length=32)
    surname = models.CharField(max_length=32)
    login = models.CharField(max_length=64, unique=True, default="")
    email = models.EmailField(unique=True, blank=False, default="")
    ZIP_code = models.CharField(max_length=7)
    city = models.CharField(max_length=32)
    street_number = models.CharField(max_length=64)
    phone_number = models.CharField(max_length=23, unique=True)

    def __str__(self):
        return str(
            str(self.name) + " " + str(self.surname) + " Tel: " + str(self.phone_number)
        )


class client(models.Model):
    name = models.CharField(max_length=32)
    surname = models.CharField(max_length=32)
    login = models.CharField(max_length=64, unique=True, default="")
    email = models.EmailField(unique=True, blank=False, default="")
    phone_number = models.CharField(max_length=23, unique=True, blank=True)

    def __str__(self):
        return str(
            str(self.name) + " " + str(self.surname) + " Tel: " + str(self.phone_number) + " E-mail: " + str(self.email)

        )

    def get_login(self):
        return self.login

    def get_email(self):
        return self.email



class service_request(models.Model):
    client_id = models.ForeignKey(client, on_delete=models.CASCADE)
    ZIP_code = models.CharField(max_length=7, blank=True)
    city = models.CharField(max_length=32, blank=True)
    street_number = models.CharField(max_length=64, blank=True)
    date_of_request = models.DateTimeField('Date of service request')
    date_of_completion = models.DateTimeField('Date of service request completed', blank=True, null=True)

    def __str__(self):
        return str(self.client_id)

    def get_date_to_client(self):
        return self.date_of_request


class hardware(models.Model):
    request_id = models.ForeignKey(service_request, on_delete=models.CASCADE)
    brand = models.CharField(max_length=32, blank=True)
    model = models.CharField(max_length=32)
    serial_number = models.CharField(max_length=64)
    client_description = models.CharField(max_length=1024)
    warranty = models.BooleanField

    def __str__(self):
        return str(
            str(self.brand) + " " + str(self.model)
        )
    def get_brand(self):
        return self.brand

    def get_all_info(self):
        return str(
            str(self.brand) + " " + str(self.model) + " s/n:" + str(self.serial_number)
        )

class repair_part(models.Model):
    brand = models.CharField(max_length=32)
    producer_num = models.CharField(max_length=64)
    description = models.CharField(max_length=64)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    stock = models.IntegerField(null=True)

    def __str__(self):
        return str(
            str(self.brand) + " " + str(self.description)
        )


class hardware_fault(models.Model):
    hardware_id = models.ForeignKey(hardware, on_delete=models.CASCADE)
    repair_part_id = models.ForeignKey(repair_part, on_delete=models.CASCADE, blank=True, null=True)
    employee_id = models.ForeignKey(employee, on_delete=models.CASCADE, blank=True)
    professional_description = models.CharField(max_length=512)
    repair_price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return str(
            str(self.hardware_id) + ": " + str(self.professional_description)
        )


class specialization(models.Model):
    name = models.CharField(max_length=64)
    hourly_wage = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return str(
            str(self.name) + " " + str(self.hourly_wage)
        )


class employee_specialization(models.Model):
    employee_id = models.ForeignKey(employee, on_delete=models.CASCADE)
    specialization_id = models.ForeignKey(specialization, on_delete=models.CASCADE)

    def __str__(self):
        return str(
            str(self.employee_id) + " " + str(self.specialization_id)
        )

Punkt_Serwisowy/electronic_service/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_list_or_404, redirect
from .models import *
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.models import User

# OLD VERSION NOT RECOMMEND TO USE IN FUTURE PROJECTS:
# def index(request):
#     client_list = client.objects.all()
#     client_list_logins = []
#     for c in client_list:
#         client_list_logins.append(c.get_login())
#         print(client_list_logins)
#
#     return render(request, 'electronic_service/indexcopy.html', {"client_list": client_list_logins})

def index(request):
    username = request.user.username
    try:
        user_logged_in = client.objects.get(login=username)
    except(client.DoesNotExist):
        try:
            employee_logged_in = employee.objects.get(login=username)
        except(employee.DoesNotExist):
            return render(request, 'electronic_service/index.html')

        else:
            return render(request, 'electronic_service/employee_main_page.html')
    else:
        return render(request, 'electronic_service/index.html')


def profile(request):
    username = request.user.username
    try:
        user_logged_in = client.objects.get(login=username)
        s_r_l = service_request.objects.filter(client_id=user_logged_in.id)
        s_r_h_l = hardware.objects.all()

    except(client.DoesNotExist):
        return HttpResponse("Unknown Error ¯\_( ͡° ͜ʖ ͡°)_/¯")
    else:
        return render(request, 'electronic_service/user_profile.html',
                      {'user_client': user_logged_in, 'service_request_list': s_r_l,
                       'service_request_hardware_list': s_r_h_l})


def profile_edit(request):
    username = request.user.username
    try:
        user_logged_in = client.objects.get(login=username)
        return render(request, 'electronic_service/user_profile_edit.html', {'user_client': user_logged_in})
    except(client.DoesNotExist):
        return HttpResponse("Employee page edit")


def profile_edit_result(request):
    client_list = client.objects.all()
    new_login = request.POST["F_login"]
    curent_user = request.user
    curent_client = client.objects.get(login=curent_user.username)

    var = False

    for c in client_list:
        if c.login == new_login and new_login != curent_user.username:
            var = True

    if not var:
        curent_client.name = request.POST['F_name']
        curent_client.surname = request.POST['F_surname']
        curent_client.login = request.POST['F_login']
        curent_client.email = request.POST['F_email']
        curent_client.phone_number = request.POST['F_phone_number']
        curent_client.save()

        curent_user.username = request.POST['F_login']
        curent_user.email = request.POST['F_email']
        curent_user.first_name = request.POST['F_name']
        curent_user.last_name = request.POST['F_surname']
        curent_user.save()

        return redirect(reverse('electronic_service:profile'))
    else:
        return render(request, 'electronic_service/user_profile_edit.html', {
            'error_message': "Login is in use, try something different!",
            'user_client': curent_client,
        })

def profile_delete(request):
    username = request.user.username
    try:
        user_logged_in = client.objects.get(login=username)
        service_request_list = service_request.objects.filter(client_id=user_logged_in)
        return render(request, 'electronic_service/user_profile_delete.html', {'user_client': user_logged_in, 'services_list': service_request_list})
    except(client.DoesNotExist):
        return HttpResponse("Unknown error")

def profile_delete_result(request):
    username = request.user.username
    try:
        client_logged_in = client.objects.get(login=username)
        user_logged_in = User.objects.get(username=username)
        client_logged_in.delete()
        user_logged_in.delete()
        return render(request, "electronic_service/user_profile_delete_result.html")
    except(client.DoesNotExist or User.DoesNotExist):
        return HttpResponse("Unknown error")

def make_request(request):
    try:
        username = request.user.username
        user_logged_in = client.objects.get(login=username)

    except(client.DoesNotExist):
        messages.success(request, "First login as client")
        return redirect(reverse('login'))
    else:
        return render(request, 'electronic_service/make_request.html', {'user_client': user_logged_in})


def make_request_result(request):
    curent_user = request.user
    curent_client = client.objects.get(login=curent_user.username)
    new_request = service_request(
        client_id=curent_client,
        street_number=request.POST['F_street_number'],
        city=request.POST['F_city'],
        ZIP_code=request.POST['F_ZIP_code'],
        date_of_request=datetime.now(),
    )
    new_request.save()
    return render(request, 'electronic_service/add_request_hardware.html', {'new_request': new_request})


def add_request_hardware(request, request_id):
    curent_request = service_request.objects.get(pk=request_id)
    new_hardware = hardware(
        request_id=curent_request,
        brand=request.POST['F_brand'],
        model=request.POST['F_model'],
        serial_number=request.POST['F_serial_number'],
        client_description=request.POST['F_fault_description'],
    )
    new_hardware.save()

    if 'Continue' in request.POST:
        return render(request, 'electronic_service/add_request_hardware.html', {'new_request': curent_request})
    elif 'That is all' in request.POST:
        return redirect(reverse('electronic_service:profile'))
    else:
        return HttpResponse("Unknown Error ¯\_( ͡° ͜ʖ ͡°)_/¯")


def client_list_E_P(request):
    client_list = client.objects.all()
    return render(request, 'electronic_service/client_list_E_P.html', {'client_list': client_list})


def hardware_list_E_P(request):
    hardware_list = hardware.objects.all()
    return render(request, 'electronic_service/hardware_list_E_P.html', {'hardware_list': hardware_list})

def hardware_fault_list_E_P(request):
    hardware_list = hardware_fault.objects.all()
    return render(request, 'electronic_service/hardware_fault_list_E_P.html', {'hardware_list': hardware_list})

def request_list_E_P(request):
    request_list = service_request.objects.all()
    return render(request, 'electronic_service/service_request_list_E_P.html', {'request_list': request_list})

def spare_parts_list_E_P(request):
    spare_parts_list = repair_part.objects.all()
    return render(request, 'electronic_service/spare_parts_list_E_P.html', {"spare_parts_list": spare_parts_list})


def profile_E_P(request):
    username = request.user.username
    try:
        user_logged_in = employee.objects.get(login=username)
    #     Specialization information needs to be added

    except(employee.DoesNotExist):
        return HttpResponse("Unknown Error ¯\_( ͡° ͜ʖ ͡°)_/¯")
    else:
        return render(request, 'electronic_service/employee_profile.html',
                      {'user_employee': user_logged_in})


def profile_edit_E_P(request):
    username = request.user.username
    try:
        user_logged_in = employee.objects.get(login=username)
        return render(request, 'electronic_service/employyee_profile_edit.html', {'user_employee': user_logged_in})
    except(employee.DoesNotExist):
        return HttpResponse("Unknown Error ¯\_( ͡° ͜ʖ ͡°)_/¯")


def profile_edit_result_E_P(request):
    client_list = employee.objects.all()
    new_login = request.POST["F_login"]
    curent_user = request.user
    curent_employee = employee.objects.get(login=curent_user.username)

    var = False

    for c in client_list:
        if c.login == new_login and new_login != curent_user.username:
            var = True

    if not var:
        curent_employee.name = request.POST['F_name']
        curent_employee.surname = request.POST['F_surname']
        curent_employee.login = request.POST['F_login']
        curent_employee.email = request.POST['F_email']
        curent_employee.phone_number = request.POST['F_phone_number']
        curent_employee.save()

        curent_user.username = request.POST['F_login']
        curent_user.email = request.POST['F_email']
        curent_user.first_name = request.POST['F_name']
        curent_user.last_name = request.POST['F_surname']
        curent_user.save()

        return redirect(reverse('electronic_service:employee_profile'))
    else:
        return render(request, 'electronic_service/employee_profile_edit.html', {
            'error_message': "Login is in use, try something different!",
            'user_client': curent_employee,
        })

Punkt_Serwisowy/electronic_service/templates/electronic_service/add_request_hardware.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add your faulty device</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'electronic_service/blank_style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
</head>
<body>
<div class="top_div">
    <div class="logo_img">
        <a href="{% url 'electronic_service:index' %}" title="Main page">
            <img src="{% static 'resources/logo_white.png' %}">
        </a>
        <div style="margin-left: 30px">
            TrollIT
        </div>
    </div>
</div>

<div class="color_scheme_1" style="margin-top: calc(50px + 9vh)">
    <strong>Step II:</strong>
    <div>
        Enter your hardware data
    </div>
    <form action="{% url 'electronic_service:add_request_hardware' new_request.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            {% if error_message %}<p>{{ error_message }}</p>{% endif %}
            <div class="request_data_row">Device brand:</div>
            <input type="text" name="F_brand" required><br>
            <div class="request_data_row">Device model:</div>
            <input type="text" name="F_model" required><br>
            <div class="request_data_row">Device serial number:</div>
            <input type="text" name="F_serial_number" required><br>
            <div class="request_data_row">What is wrong with the device?</div>
            <input type="text" name="F_fault_description" required><br>

        </fieldset>

        <button type="submit" name="Continue" style="font-size: 25px">Continue</button>
        <button type="submit" name="That is all" style="font-size: 25px">That_is_all</button>
    </form>
</div>
<footer>
    Made by Dariusz Rzeźnik 2022<br>
</footer>
</body>

</html>

Punkt_Serwisowy/electronic_service/templates/electronic_service/employee_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{user.username}} profile</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'electronic_service/user_profile_style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
</head>
<body>
    <div class="top_div">
        <div class="logo_img">
            <a href="{% url 'electronic_service:index' %}" title="Main page">
                <img src="{% static 'resources/logo_white.png' %}">
            </a>
            <div style="margin-left: 30px">
                TrollIT
            </div>
        </div>
    </div>
    <div class="color_scheme_1" style="margin-top: calc(50px + 9vh)">
        <div>
            <strong>{{user_employee.name}} {{user_employee.surname}} account:</strong>
        </div>
        <div class="user_data_row">
            <div class="data_column">
                Name:
            </div>
            <div>
                {{ user_employee.name }}
            </div>
        </div>
        <div class="user_data_row">
            <div class="data_column">
                Surname:
            </div>
            <div>
                {{ user_employee.surname }}
            </div>
        </div>
        <div class="user_data_row">
            <div class="data_column">
                Login:
            </div>
            <div>
                {{ user_employee.login }}
            </div>
        </div>
        <div class="user_data_row">
            <div class="data_column">
                E-mail:
            </div>
            <div>
                {{ user_employee.email }}
            </div>
        </div>
        <div class="user_data_row">
            <div class="data_column">
                Phone number:
            </div>
            <div>
                {{ user_employee.phone_number }}
            </div>
        </div>
        <div style="font-size: 30px; display: flex; justify-content: center; flex-wrap: wrap">
            <a href="{% url 'electronic_service:employee_profile_edit' %}" style="color: white;
            background-color: rgb(25, 27, 179); padding: 5px; margin: 5px 5px 5px 5px">Edit your profile</a>
            <a href="{% url 'password_reset' %}" style="color: white;
            background-color: rgb(25, 27, 179); padding: 5px; margin: 5px 5px 5px 5px">Change your password</a>
        </div>
    </div>

    <div class="color_scheme_1">
        <div style="display: flex; justify-content: center; justify-content: space-between; margin: 5px 5px 5px 5px">
            Your specializations:
        </div>
            WORK IN PROGRESS
    </div>
<footer>
    Made by Dariusz Rzeźnik 2022<br>
</footer>
</body>
</html>

Punkt_Serwisowy/electronic_service/templates/electronic_service/employyee_profile_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{user.username}} profile edit page</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'electronic_service/user_profile_edit_style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
</head>
<body>
<div class="top_div">
    <div class="logo_img">
        <a href="{% url 'electronic_service:index' %}" title="Main page">
            <img src="{% static 'resources/logo_white.png' %}">
        </a>
        <div style="margin-left: 30px">
            TrollIT
        </div>
    </div>
</div>
<div class="color_scheme_1" style="margin-top: calc(50px + 9vh)">
    <div>
        <strong>{{user_employee.name}} {{user_employee.surname}} account edit page</strong>
    </div>
    <form action="{% url 'electronic_service:employee_profile_edit_result' %}" method="post">
        {% csrf_token %}
        <fieldset>
            {% if error_message %}<p>{{ error_message }}</p>{% endif %}
            <div class="user_data_row">Name:</div>
            <input type="text" name="F_name" placeholder="Name" required value={{ user_employee.name }}><br>
            <div class="user_data_row">Surname:</div>
            <input type="text" name="F_surname" placeholder="Surname" required value={{ user_employee.surname }}><br>
            <div class="user_data_row">Login:</div>
            <input type="text" name="F_login" placeholder="Login" required value={{ user_employee.login }}><br>
            <div class="user_data_row">E-mail:</div>
            <input type="text" name="F_email" placeholder="E-mail" required value={{ user_employee.email }}><br>
            <div class="user_data_row">Phone number:</div>
            <input type="text" name="F_phone_number" placeholder="Your phone number" required value={{ user_employee.phone_number }}><br>
        </fieldset>
        <input type="submit" value="Save changes" style="font-size: 32px">

    </form>
</div>
<footer>
    Made by Dariusz Rzeźnik 2022<br>
</footer>
</body>
</html>

Punkt_Serwisowy/electronic_service/templates/electronic_service/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TrolIT</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'electronic_service/index_style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">


</head>
<body>
<div class="top_div">
    <div class="logo_img">
        <a href="{% url 'electronic_service:index' %}" title="Main page">
            <img src="{% static 'resources/logo_white.png' %}">
        </a>
        <div style="margin-left: 30px">
            TrollIT
        </div>
    </div>

    {% if user.is_authenticated %}
    <div class="user_info_col">
        Hi {{ user.username }}!<br>
        <a href="{% url 'logout' %}">Log Out</a>
        <a href="{% url 'electronic_service:profile' %}">My account</a>
    </div>

    {% else %}
    <div class="user_info_col">
        You are not logged in<br>

        <a href="{% url 'login' %}">Log In </a>
        or
        <a href="{% url 'account:signup' %}"> Signup</a>
    </div>
    {% endif %}


</div>

<div class="banner_image">
    <div class="a123">
        REPAIR AND SERVICE OF ELECTRICAL AND ELECTRONIC EQUIPMENT
    </div>
</div>

<div class="color_scheme_1" style="margin-top: -70px;">
    <strong>Our specialized staff will take care of your equipment using the appropriate tools</strong>
</div>

<div class="color_scheme_1 employee_div_1">
    <div>
        <img src="{% static 'resources/komp.png' %}">
    </div>
    <div>
        We provide <strong>post-warranty</strong> service<br>
    </div>
</div>

<div class="color_scheme_1 employee_div_2">
    <div>
        We only use <strong>original</strong> repair parts
    </div>
    <div>
        <img src="{% static 'resources/komp2.png' %}">
    </div>

</div>

<div class="color_scheme_1">

<!--    <button onclick="darkModeToggle()">Dark mode</button><br>-->

    How does it work?<br>
    <ol style="font-size: calc(15px + 1vh)">
        <li><strong>Registration</strong><br>First create an account, then make a request where you will add all your faulty devices</li>
        <li><strong>Delivery of the device</strong><br>After making request you will recive e-mail from our delivery partner with all information about sending us your devices</li>
        <li><strong>Diagnosis</strong><br>After a precise diagnosis of the device, we contact you to provide detailed information about the repair process and present a cost estimate.</li>
        <li><strong>Devices repair</strong><br>After accepting the costs, we proceed to repair. The device is then tested again. A fully functional device is ready for courier shipment to the address provided in the service request.</li>
    </ol>


</div>
<div class="color_scheme_1" style="display: flex; justify-content: center">
    <div>
        <a href="{% url 'electronic_service:make_request' %}" style="color: white; background-color: rgb(25, 27, 179); padding: 3px">Make a request</a>
    </div>
</div>

<footer>
    Made by Dariusz Rzeźnik 2022<br>
</footer>

<script>
        function darkModeToggle() {
            const collection = document.getElementsByClassName("color_scheme_1");
            for (let i = 0; i < collection.length; i++) {
                collection[i].classList.toggle("dark-mode_color_scheme_1");
            }
            const top_div = document.getElementsByClassName('top_div');
            for (let i = 0; i < top_div.length; i++) {
                top_div[i].classList.toggle("dark-mode_top_div")
            }
            var body_BG = document.querySelector('body')
            body_BG.classList.toggle('dark-mode_body')
            const banner = document.getElementsByClassName('banner_image');
            for (let i = 0; i < banner.length; i++) {
                banner[i].classList.toggle("dark-mode_banner_image")
            }
            const e_pic1 = document.getElementsByClassName("employee_div_1")
            for (let i=0; i<e_pic1.length; i++){
                e_pic1[i].classList.toggle("dark-mode_employee_div")
            }
            const e_pic2 = document.getElementsByClassName("employee_div_2")
            for (let i=0; i<e_pic2.length; i++){
                e_pic2[i].classList.toggle("dark-mode_employee_div")
            }
        }
    </script>
</body>
</html>

Punkt_Serwisowy/electronic_service/templates/electronic_service/user_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{user.username}} profile</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'electronic_service/user_profile_style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
</head>
<body>
    <div class="top_div">
        <div class="logo_img">
            <a href="{% url 'electronic_service:index' %}" title="Main page">
                <img src="{% static 'resources/logo_white.png' %}">
            </a>
            <div style="margin-left: 30px">
                TrollIT
            </div>
        </div>
    </div>
    <div class="color_scheme_1" style="margin-top: calc(50px + 9vh)">
        <div>
            <strong>{{user_client.name}} {{user_client.surname}} account:</strong>
        </div>
        <div class="user_data_row">
            <div class="data_column">
                Name:
            </div>
            <div>
                {{ user_client.name }}
            </div>
        </div>
        <div class="user_data_row">
            <div class="data_column">
                Surname:
            </div>
            <div>
                {{ user_client.surname }}
            </div>
        </div>
        <div class="user_data_row">
            <div class="data_column">
                Login:
            </div>
            <div>
                {{ user_client.login }}
            </div>
        </div>
        <div class="user_data_row">
            <div class="data_column">
                E-mail:
            </div>
            <div>
                {{ user_client.email }}
            </div>
        </div>
        <div class="user_data_row">
            <div class="data_column">
                Phone number:
            </div>
            <div>
                {{ user_client.phone_number }}
            </div>
        </div>
        <div style="font-size: 30px; display: flex; justify-content: center; flex-wrap: wrap">
            <a href="{% url 'electronic_service:profile_edit' %}" style="color: white;
            background-color: rgb(25, 27, 179); padding: 5px; margin: 5px 5px 5px 5px">Edit your profile</a>
            <a href="{% url 'password_reset' %}" style="color: white;
            background-color: rgb(25, 27, 179); padding: 5px; margin: 5px 5px 5px 5px">Change your password</a>
            <a href="{% url 'electronic_service:profile_delete' %}" style="color: white;
            background-color: rgb(25, 27, 179); padding: 5px; margin: 5px 5px 5px 5px">Delete your account</a>
        </div>
    </div>

    <div class="color_scheme_1">
        <div style="display: flex; justify-content: center; justify-content: space-between; margin: 5px 5px 5px 5px">
            Your repairs
        </div>

        <div style="font-size: calc(15px + 1vh);">
            {% if service_request_list %}
                {% for s_r in service_request_list %}
                    <li>{{s_r.get_date_to_client |date:"j-n-Y"}}:
                    {% for h in service_request_hardware_list %}
                        {% if s_r == h.request_id%}
                            {{h.brand}} {{h.model}}
                        {% endif %}
                    {% endfor %}
                    {% if s_r.date_of_completion %}
                        Completed, ready to deliver
                    {% endif %}
                    </li>
                {% endfor %}
                <div style="margin-top: 15px; margin-bottom: 5px">
                    <a href="{% url 'electronic_service:make_request' %}" style="color: white; background-color: rgb(25, 27, 179); padding: 3px">Add another service request</a>
                </div>
            {% else %}
                You don't have any service requests <a href="{% url 'electronic_service:make_request' %}" style="color: white; background-color: rgb(25, 27, 179); padding: 3px">Add one now!</a>
            {% endif %}
        </div>
    </div>
<footer>
    Made by Dariusz Rzeźnik 2022<br>
</footer>
</body>
</html>